

--DROP SCHEMA IF EXISTS SMS_SCHEMA;
--CREATE SCHEMA SMS_SCHEMA AUTHORIZATION SA;
--SET SCHEMA SMS_SCHEMA;

CREATE SEQUENCE "T_USER_SEQ" INCREMENT BY 1 START WITH 1;

CREATE TABLE T_USER (
  C_USER_ID NUMBER PRIMARY KEY,
  C_USER_LOGIN VARCHAR(16) NOT NULL,
  C_USER_NAME VARCHAR(100) NOT NULL,
  CONSTRAINT I_USER_LOGIN_UC UNIQUE (C_USER_LOGIN),
  CONSTRAINT I_USER_NAME_UC UNIQUE (C_USER_NAME)
); 

CREATE TABLE T_USER_SECURITY (
  C_USER_ID NUMBER NOT NULL REFERENCES T_USER (C_USER_ID) ON DELETE CASCADE,
  C_USER_PASSWORD VARCHAR(16) NOT NULL,
  C_USER_AUTH_STRING VARCHAR(255) NOT NULL,
  C_USER_ROLE VARCHAR(10) NOT NULL,
  CONSTRAINT I_USER_ID_UC UNIQUE (C_USER_ID)
);
